'use client'

import { useState } from 'react'
import { Brain, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'BPI Account', type:Closed, period:'Main', generatedOn:'2026-02-12', generatedBy:'Default'},
    {id:'r2', name:'Default', type:Low, period:'BPI Account', generatedOn:'2026-03-18', generatedBy:'Standard'},
    {id:'r3', name:'Metro Manila', type:Approved, period:'BPI Account', generatedOn:'2026-03-26', generatedBy:'Metro Manila'},
    {id:'r4', name:'Standard', type:Connected, period:'Monthly', generatedOn:'2026-02-04', generatedBy:'BPI Account'},
    {id:'r5', name:'Active Item', type:Open, period:'Active Item', generatedOn:'2026-01-19', generatedBy:'Q1 2026'},
    {id:'r6', name:'Sample Entry', type:Open, period:'Acme Corp', generatedOn:'2026-02-01', generatedBy:'Standard'},
    {id:'r7', name:'Acme Corp', type:In_Stock, period:'Sample Entry', generatedOn:'2026-02-02', generatedBy:'Metro Manila'},
    {id:'r8', name:'Standard', type:Filed, period:'Active Item', generatedOn:'2026-03-14', generatedBy:'Sample Entry'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Anomaly Detection"
      section="AI Analytics"
      icon={<Brain size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={['name','period','generatedBy']}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}