'use client'

import PageDocumentation from '@/components/owner/PageDocumentation'

export default function Page() {
  return (
    <PageDocumentation
      title="My Tasks"
      module="TASKS"
      breadcrumb="Tasks & Approvals / My Work / My Tasks"
      purpose="My Tasks is the personal task management inbox showing all tasks currently assigned to the logged-in user across all modules. Users can view, filter, prioritize, and action their tasks without having to navigate through individual modules. Tasks come from multiple sources: manually created tasks, tasks generated by workflow automations, period-close checklists, and follow-up reminders."
      components={[
        { name: 'Task List', description: 'Filterable, sortable list of all assigned tasks with status indicators, priority flags, due dates, and linked record.' },
        { name: 'Task Detail Panel', description: 'Slide-in panel showing full task details, description, linked record, comments thread, attachments, and activity history.' },
        { name: 'Priority Filter Bar', description: 'Quick-filter chips: All, Overdue, Due Today, High Priority, By Module, Completed.' },
        { name: 'Bulk Actions Toolbar', description: 'Select multiple tasks for bulk complete, reassign, snooze, or delete.' },
        { name: 'Add Task Button', description: 'Create a new manual task with title, assignee, due date, priority, and linked record.' },
      ]}
      tabs={['All Tasks', 'Overdue', 'Due Today', 'This Week', 'Completed']}
      features={[
        'Tasks aggregated from all modules in one list',
        'Priority levels: Critical, High, Medium, Low',
        'Due date tracking with overdue highlighting',
        'Linked record navigation (click to view invoice, bill, etc.)',
        'Comment thread on each task for collaboration',
        'Bulk complete and reassign actions',
        'Recurring task support',
      ]}
      dataDisplayed={[
        'Task title, description, and status',
        'Assigned by (user or system/automation)',
        'Due date and days overdue/remaining',
        'Priority level (Critical / High / Medium / Low)',
        'Linked module and record (e.g., Invoice #1042)',
        'Last activity timestamp',
      ]}
      userActions={[
        'Mark task as complete',
        'Change priority level',
        'Reassign task to another user',
        'Add comment to task thread',
        'Attach a file to the task',
        'Set or change due date',
        'Create new manual task',
        'Filter tasks by module, priority, or due date',
      ]}
      relatedPages={[
        { label: 'My Approvals', href: '/tasks-approvals/my-work/my-approvals' },
        { label: 'My Exceptions', href: '/tasks-approvals/my-work/my-exceptions' },
        { label: 'Team Tasks', href: '/tasks-approvals/management/team-tasks' },
        { label: 'Completed Tasks', href: '/tasks-approvals/history/completed-tasks' },
      ]}
    />
  )
}

