'use client'

import PageDocumentation from '@/components/owner/PageDocumentation'

export default function Page() {
  return (
    <PageDocumentation
      title="Period Reports"
      module="ACCOUNTING"
      breadcrumb="Accounting / Period Close / Period Reports"
      purpose="Period Reports is the close-time reporting package generator. At month-end and year-end, controllers and CFOs generate a comprehensive set of financial reports in a single action — balance sheet, P&L, cash flow statement, trial balance, AR aging, AP aging, and any configured management reports. Reports are generated for the closed period, saved to the report archive, and can be distributed to stakeholders as a PDF pack."
      components={[
        { name: 'Report Package Builder', description: 'Select which reports to include in the period-end package and configure any filters (entity, department).' },
        { name: 'Generate Package Button', description: 'One-click generation of all selected reports for the specified period.' },
        { name: 'Package Archive', description: 'All previously generated period-end report packages with period, generation date, generated by, and download link.' },
        { name: 'Distribution List', description: 'Configure which stakeholders receive the report package automatically by email upon generation.' },
      ]}
      tabs={['Generate Package', 'Archive', 'Distribution', 'Settings']}
      features={[
        'One-click period-end report package generation',
        'Configurable report set per package',
        'Automatic email distribution to stakeholders',
        'Period-end report archive with history',
        'PDF and Excel formats supported',
        'Comparative period option (vs. prior period or budget)',
      ]}
      dataDisplayed={[
        'All reports included in the configured package',
        'Period-end package generation history',
        'Package distribution status',
        'Archive of all prior period packages',
      ]}
      userActions={[
        'Configure period-end report package',
        'Generate period-end reports for a period',
        'Distribute package to stakeholders',
        'Download a prior period package',
        'Set up automatic distribution list',
      ]}
      relatedPages={[
        { label: 'Close Checklist', href: '/accounting/period-close/close-checklist' },
        { label: 'Lock Periods', href: '/accounting/period-close/lock-periods' },
        { label: 'Balance Sheet', href: '/reporting/reports-center/financial-statements/balance-sheet' },
        { label: 'P&L Report', href: '/reporting/reports-center/financial-statements/profit-and-loss' },
      ]}
    />
  )
}

