'use client'

import { useState } from 'react'
import { Package, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Active Item', type:Pending, period:'Active Item', generatedOn:'2026-02-27', generatedBy:'Active Item'},
    {id:'r2', name:'Sample Entry', type:Current, period:'Standard', generatedOn:'2026-01-15', generatedBy:'Sample Entry'},
    {id:'r3', name:'BPI Account', type:Medium, period:'Primary', generatedOn:'2026-02-09', generatedBy:'Main'},
    {id:'r4', name:'Sample Entry', type:Medium, period:'Standard', generatedOn:'2026-03-13', generatedBy:'Active Item'},
    {id:'r5', name:'Acme Corp', type:In_Stock, period:'Standard', generatedOn:'2026-03-06', generatedBy:'Metro Manila'},
    {id:'r6', name:'Active Item', type:Approved, period:'Main', generatedOn:'2026-01-10', generatedBy:'Main'},
    {id:'r7', name:'Primary', type:Open, period:'BPI Account', generatedOn:'2026-03-02', generatedBy:'Monthly'},
    {id:'r8', name:'Default', type:Completed, period:'BPI Account', generatedOn:'2026-02-02', generatedBy:'Standard'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Inventory Valuation"
      section="Inventory"
      icon={<Package size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={['name','period','generatedBy']}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}