'use client'

import { useState } from 'react'
import { Landmark, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Acme Corp', type:Enabled, period:'Sample Entry', generatedOn:'2026-01-03', generatedBy:'Metro Manila'},
    {id:'r2', name:'Sample Entry', type:Closed, period:'Standard', generatedOn:'2026-01-10', generatedBy:'Main'},
    {id:'r3', name:'Monthly', type:High, period:'Primary', generatedOn:'2026-02-06', generatedBy:'Main'},
    {id:'r4', name:'Metro Manila', type:Pending, period:'BPI Account', generatedOn:'2026-02-06', generatedBy:'Q1 2026'},
    {id:'r5', name:'Primary', type:High, period:'Primary', generatedOn:'2026-03-05', generatedBy:'Default'},
    {id:'r6', name:'Monthly', type:Connected, period:'BPI Account', generatedOn:'2026-03-02', generatedBy:'Sample Entry'},
    {id:'r7', name:'Primary', type:Paid, period:'Monthly', generatedOn:'2026-01-04', generatedBy:'Sample Entry'},
    {id:'r8', name:'Default', type:High, period:'Monthly', generatedOn:'2026-02-28', generatedBy:'Primary'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Cash Position"
      section="Banking & Cash"
      icon={<Landmark size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={['name','period','generatedBy']}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}