'use client'

import { useState } from 'react'
import { Package, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Q1 2026', type:Approved, period:'Standard', generatedOn:'2026-01-21', generatedBy:'Active Item'},
    {id:'r2', name:'Main', type:In_Stock, period:'Standard', generatedOn:'2026-02-21', generatedBy:'Standard'},
    {id:'r3', name:'BPI Account', type:In_Stock, period:'Monthly', generatedOn:'2026-02-16', generatedBy:'Default'},
    {id:'r4', name:'Standard', type:Current, period:'Q1 2026', generatedOn:'2026-03-21', generatedBy:'Acme Corp'},
    {id:'r5', name:'Standard', type:Draft, period:'Main', generatedOn:'2026-03-23', generatedBy:'Q1 2026'},
    {id:'r6', name:'Main', type:Completed, period:'Q1 2026', generatedOn:'2026-03-22', generatedBy:'Acme Corp'},
    {id:'r7', name:'Monthly', type:Closed, period:'Standard', generatedOn:'2026-03-22', generatedBy:'Sample Entry'},
    {id:'r8', name:'Main', type:Approved, period:'Main', generatedOn:'2026-02-18', generatedBy:'Q1 2026'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Turnover"
      section="Inventory"
      icon={<Package size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
