-- Drop onboarding-related columns from tenant in an idempotent way
BEGIN;
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "businessType";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "industry";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "startDate";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "country";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "address";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "taxId";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "vatRegistered";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "vatRate";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "pricesInclusive";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "taxFilingFrequency";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "taxExempt";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "logoUrl";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "invoicePrefix";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "defaultPaymentTerms";
ALTER TABLE IF EXISTS "Tenant" DROP COLUMN IF EXISTS "accountingMethod";
COMMIT;