'use client'

import { useState } from 'react'
import { Shield, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'BPI Account', type:Draft, period:'Active Item', generatedOn:'2026-01-15', generatedBy:'Q1 2026'},
    {id:'r2', name:'Acme Corp', type:Approved, period:'Metro Manila', generatedOn:'2026-03-17', generatedBy:'BPI Account'},
    {id:'r3', name:'Acme Corp', type:Paid, period:'Monthly', generatedOn:'2026-01-21', generatedBy:'Acme Corp'},
    {id:'r4', name:'Active Item', type:Connected, period:'Main', generatedOn:'2026-02-03', generatedBy:'Metro Manila'},
    {id:'r5', name:'Main', type:Closed, period:'Monthly', generatedOn:'2026-01-04', generatedBy:'Standard'},
    {id:'r6', name:'Metro Manila', type:Closed, period:'Acme Corp', generatedOn:'2026-01-25', generatedBy:'Acme Corp'},
    {id:'r7', name:'Monthly', type:High, period:'Standard', generatedOn:'2026-02-08', generatedBy:'Acme Corp'},
    {id:'r8', name:'Active Item', type:Connected, period:'Sample Entry', generatedOn:'2026-01-28', generatedBy:'Metro Manila'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Sox Compliance"
      section="Compliance"
      icon={<Shield size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
