'use client'

import { useState } from 'react'
import { Package, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Standard', type:Low, period:'Acme Corp', generatedOn:'2026-03-27', generatedBy:'Primary'},
    {id:'r2', name:'Acme Corp', type:Completed, period:'Primary', generatedOn:'2026-03-20', generatedBy:'Main'},
    {id:'r3', name:'Sample Entry', type:Paid, period:'Default', generatedOn:'2026-01-08', generatedBy:'Primary'},
    {id:'r4', name:'Acme Corp', type:Medium, period:'Monthly', generatedOn:'2026-01-06', generatedBy:'Main'},
    {id:'r5', name:'Acme Corp', type:Current, period:'Default', generatedOn:'2026-02-19', generatedBy:'BPI Account'},
    {id:'r6', name:'BPI Account', type:Open, period:'Q1 2026', generatedOn:'2026-02-15', generatedBy:'Monthly'},
    {id:'r7', name:'Sample Entry', type:Pending, period:'Sample Entry', generatedOn:'2026-02-07', generatedBy:'Main'},
    {id:'r8', name:'Metro Manila', type:Current, period:'Default', generatedOn:'2026-01-15', generatedBy:'Acme Corp'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Overstock Analysis"
      section="Inventory"
      icon={<Package size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={['name','period','generatedBy']}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}