-- Migration generated by scripts/generate-add-tenant-fks-migration.js
DO $$ BEGIN
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name = 'Budget') THEN
		ALTER TABLE public."Budget" VALIDATE CONSTRAINT "Budget_tenant_fkey";
	END IF;
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name = 'FixedAsset') THEN
		ALTER TABLE public."FixedAsset" VALIDATE CONSTRAINT "FixedAsset_tenant_fkey";
	END IF;
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name = 'FixedAssetCategory') THEN
		ALTER TABLE public."FixedAssetCategory" VALIDATE CONSTRAINT "FixedAssetCategory_tenant_fkey";
	END IF;
END$$;
