'use client'

import { useState } from 'react'
import { Puzzle, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'
import { statusColors, badgeColors } from '@/components/owner/statusColors'

const columns = [
    { key: 'name', label: 'Report', type: 'text', sortable: true },
    { key: 'type', label: 'Type', type: 'badge', badgeColors },
    { key: 'period', label: 'Period', type: 'text' },
    { key: 'generatedOn', label: 'Generated', type: 'date' },
    { key: 'generatedBy', label: 'Generated By', type: 'text' }
]

const mockData = [
    { id: 'r1', name: 'Sample Entry', type: 'Operating', period: 'Active Item', generatedOn: '2026-03-25', generatedBy: 'Main' },
    { id: 'r2', name: 'BPI Account', type: 'Direct', period: 'Monthly', generatedOn: '2026-03-02', generatedBy: 'Acme Corp' },
    { id: 'r3', name: 'Active Item', type: 'Fixed', period: 'Primary', generatedOn: '2026-03-17', generatedBy: 'Default' },
    { id: 'r4', name: 'General', type: 'Standard', period: 'Default', generatedOn: '2026-01-07', generatedBy: 'Acme Corp' },
    { id: 'r5', name: 'Main', type: 'Direct', period: 'Active Item', generatedOn: '2026-01-02', generatedBy: 'Default' },
    { id: 'r6', name: 'Q1 2026', type: 'Annual', period: 'Q1 2026', generatedOn: '2026-03-03', generatedBy: 'Acme Corp' },
    { id: 'r7', name: 'Q1 2026', type: 'Variable', period: 'Monthly', generatedOn: '2026-02-27', generatedBy: 'Default' },
    { id: 'r8', name: 'Q1 2026', type: 'Revenue', period: 'Main', generatedOn: '2026-03-02', generatedBy: 'General' }
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Connection Health"
      section="Apps & Integrations"
      icon={<Puzzle size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
      summaryCards={[
        { label: 'Total Records', value: 8, icon: <List size={16}/>, bg: 'bg-emerald-100', iconColor: 'text-emerald-600' },
        { label: 'Active', value: 6, icon: <CheckCircle size={16}/>, bg: 'bg-blue-100', iconColor: 'text-blue-600' },
        { label: 'This Month', value: 3, icon: <Calendar size={16}/>, bg: 'bg-amber-100', iconColor: 'text-amber-600' },
      ]}
      bulkActions={[
        { label: 'Export Selected', icon: <Download size={13}/>, onClick: (ids) => {} },
        { label: 'Delete Selected', icon: <Trash2 size={13}/>, onClick: (ids) => {}, variant: 'danger' },
      ]}
      filters={[
        { key: 'date_from', label: 'Date Range', type: 'date-range' },
      ]}
      showCreate
      createLabel="Create New"
      onCreate={() => {}}
      showExport
      onRefresh={() => {}}
      rowMenuItems={(row) => [
        { label: 'View', icon: <Eye size={14}/>, onClick: () => {} },
        { label: 'Edit', icon: <Edit2 size={14}/>, onClick: () => {} },
        { label: 'Delete', icon: <Trash2 size={14}/>, onClick: () => {}, variant: 'danger' },
      ]}
    />
  )
}
