-- Migration generated by scripts/generate-add-tenant-fks-migration.js
DO $$ BEGIN
	IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'TaxRate_tenant_fkey') THEN
		ALTER TABLE public."TaxRate" VALIDATE CONSTRAINT "TaxRate_tenant_fkey";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Budget_tenant_fkey') THEN
		ALTER TABLE public."Budget" VALIDATE CONSTRAINT "Budget_tenant_fkey";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FixedAsset_tenant_fkey') THEN
		ALTER TABLE public."FixedAsset" VALIDATE CONSTRAINT "FixedAsset_tenant_fkey";
	END IF;
	IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FixedAssetCategory_tenant_fkey') THEN
		ALTER TABLE public."FixedAssetCategory" VALIDATE CONSTRAINT "FixedAssetCategory_tenant_fkey";
	END IF;
END$$;
