'use client'

import { useState } from 'react'
import { Calculator, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Metro Manila', type:Current, period:'Acme Corp', generatedOn:'2026-02-28', generatedBy:'Active Item'},
    {id:'r2', name:'Main', type:Paid, period:'Primary', generatedOn:'2026-01-11', generatedBy:'Metro Manila'},
    {id:'r3', name:'Standard', type:Connected, period:'Monthly', generatedOn:'2026-01-11', generatedBy:'Default'},
    {id:'r4', name:'Sample Entry', type:Pending, period:'Sample Entry', generatedOn:'2026-01-07', generatedBy:'Monthly'},
    {id:'r5', name:'Standard', type:Enabled, period:'Default', generatedOn:'2026-03-20', generatedBy:'Primary'},
    {id:'r6', name:'BPI Account', type:Filed, period:'Q1 2026', generatedOn:'2026-01-06', generatedBy:'Monthly'},
    {id:'r7', name:'BPI Account', type:Processing, period:'Default', generatedOn:'2026-03-26', generatedBy:'Acme Corp'},
    {id:'r8', name:'Active Item', type:Paid, period:'Metro Manila', generatedOn:'2026-01-15', generatedBy:'Standard'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Reports"
      section="Accounting"
      icon={<Calculator size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
