'use client'

import { useState } from 'react'
import { FileText, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Monthly', type:Processing, period:'BPI Account', generatedOn:'2026-02-04', generatedBy:'Sample Entry'},
    {id:'r2', name:'Default', type:Paid, period:'Primary', generatedOn:'2026-01-24', generatedBy:'Metro Manila'},
    {id:'r3', name:'BPI Account', type:Open, period:'Main', generatedOn:'2026-01-02', generatedBy:'Standard'},
    {id:'r4', name:'Active Item', type:Medium, period:'Active Item', generatedOn:'2026-03-09', generatedBy:'Main'},
    {id:'r5', name:'Q1 2026', type:Processing, period:'Standard', generatedOn:'2026-01-12', generatedBy:'Standard'},
    {id:'r6', name:'Default', type:Completed, period:'Primary', generatedOn:'2026-02-12', generatedBy:'BPI Account'},
    {id:'r7', name:'Acme Corp', type:Closed, period:'Primary', generatedOn:'2026-02-19', generatedBy:'Active Item'},
    {id:'r8', name:'BPI Account', type:Approved, period:'Acme Corp', generatedOn:'2026-01-07', generatedBy:'Main'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Audit Trail Tax Code"
      section="Tax"
      icon={<FileText size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={['name','period','generatedBy']}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}