'use client'

import { useState } from 'react'
import { Shield, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Acme Corp', type:Enabled, period:'Metro Manila', generatedOn:'2026-02-09', generatedBy:'Monthly'},
    {id:'r2', name:'Main', type:Medium, period:'Acme Corp', generatedOn:'2026-01-19', generatedBy:'Default'},
    {id:'r3', name:'Q1 2026', type:Processing, period:'Default', generatedOn:'2026-02-01', generatedBy:'Monthly'},
    {id:'r4', name:'Metro Manila', type:Closed, period:'Main', generatedOn:'2026-01-18', generatedBy:'Monthly'},
    {id:'r5', name:'BPI Account', type:Medium, period:'Q1 2026', generatedOn:'2026-02-08', generatedBy:'Primary'},
    {id:'r6', name:'Active Item', type:Open, period:'Acme Corp', generatedOn:'2026-03-04', generatedBy:'Active Item'},
    {id:'r7', name:'Default', type:Pending, period:'Metro Manila', generatedOn:'2026-03-23', generatedBy:'BPI Account'},
    {id:'r8', name:'BPI Account', type:Open, period:'Default', generatedOn:'2026-02-03', generatedBy:'Q1 2026'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Sox Controls"
      section="Compliance"
      icon={<Shield size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
