'use client'

import { useState } from 'react'
import { FolderKanban, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Monthly', type:Active, period:'Metro Manila', generatedOn:'2026-03-08', generatedBy:'BPI Account'},
    {id:'r2', name:'Metro Manila', type:Closed, period:'Acme Corp', generatedOn:'2026-01-28', generatedBy:'Standard'},
    {id:'r3', name:'Main', type:Medium, period:'Monthly', generatedOn:'2026-01-26', generatedBy:'Acme Corp'},
    {id:'r4', name:'BPI Account', type:Pending, period:'BPI Account', generatedOn:'2026-01-17', generatedBy:'Main'},
    {id:'r5', name:'Main', type:Medium, period:'BPI Account', generatedOn:'2026-03-07', generatedBy:'BPI Account'},
    {id:'r6', name:'Active Item', type:Low, period:'Metro Manila', generatedOn:'2026-03-14', generatedBy:'Active Item'},
    {id:'r7', name:'Primary', type:In_Stock, period:'Metro Manila', generatedOn:'2026-01-04', generatedBy:'Sample Entry'},
    {id:'r8', name:'Active Item', type:Pending, period:'Primary', generatedOn:'2026-02-03', generatedBy:'Sample Entry'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Profitability Report"
      section="Projects"
      icon={<FolderKanban size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
