'use client'

import { useState } from 'react'
import { Zap, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Standard', type:Medium, period:'Metro Manila', generatedOn:'2026-01-25', generatedBy:'Metro Manila'},
    {id:'r2', name:'Default', type:Current, period:'Active Item', generatedOn:'2026-03-21', generatedBy:'Metro Manila'},
    {id:'r3', name:'Acme Corp', type:Filed, period:'Active Item', generatedOn:'2026-01-13', generatedBy:'Active Item'},
    {id:'r4', name:'Default', type:Medium, period:'Acme Corp', generatedOn:'2026-01-08', generatedBy:'Default'},
    {id:'r5', name:'Sample Entry', type:In_Stock, period:'Metro Manila', generatedOn:'2026-03-05', generatedBy:'Sample Entry'},
    {id:'r6', name:'Acme Corp', type:Completed, period:'Q1 2026', generatedOn:'2026-03-19', generatedBy:'Default'},
    {id:'r7', name:'Primary', type:Paid, period:'Monthly', generatedOn:'2026-02-01', generatedBy:'Default'},
    {id:'r8', name:'Sample Entry', type:Processing, period:'Primary', generatedOn:'2026-03-01', generatedBy:'Default'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Scheduled Reports"
      section="Automation"
      icon={<Zap size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
