'use client'

import { useState } from 'react'
import { FolderKanban, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'BPI Account', type:Medium, period:'Standard', generatedOn:'2026-01-08', generatedBy:'Metro Manila'},
    {id:'r2', name:'BPI Account', type:Current, period:'BPI Account', generatedOn:'2026-03-04', generatedBy:'Q1 2026'},
    {id:'r3', name:'Monthly', type:Paid, period:'Active Item', generatedOn:'2026-03-25', generatedBy:'Default'},
    {id:'r4', name:'Monthly', type:Pending, period:'Acme Corp', generatedOn:'2026-03-10', generatedBy:'Sample Entry'},
    {id:'r5', name:'Main', type:Low, period:'Primary', generatedOn:'2026-02-19', generatedBy:'BPI Account'},
    {id:'r6', name:'BPI Account', type:Paid, period:'Active Item', generatedOn:'2026-01-19', generatedBy:'Q1 2026'},
    {id:'r7', name:'Sample Entry', type:Connected, period:'Default', generatedOn:'2026-03-10', generatedBy:'Monthly'},
    {id:'r8', name:'Sample Entry', type:Processing, period:'BPI Account', generatedOn:'2026-01-16', generatedBy:'Monthly'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Resource Utilization"
      section="Projects"
      icon={<FolderKanban size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
