'use client'

import PageDocumentation from '@/components/owner/PageDocumentation'

export default function Page() {
  return (
    <PageDocumentation
      title="Estimate Settings"
      module="SALES"
      breadcrumb="Sales / Estimates / Estimate Settings"
      purpose="Estimate Settings configures the defaults and preferences for all estimate documents — including the default expiry period (e.g., 30 days from issue), estimate numbering format, default terms and conditions text, default notes, company branding on the PDF, default line item taxes, and email template for sending estimates to customers. These settings ensure consistency across all estimates generated by the team."
      components={[
        { name: 'Numbering Settings', description: 'Set estimate number prefix, starting number, and auto-increment pattern (e.g., EST-2025-0001).' },
        { name: 'Default Expiry', description: 'Set default validity period in days for all new estimates.' },
        { name: 'Terms & Conditions', description: 'Rich text editor for the standard T&C text that appears on all estimate documents.' },
        { name: 'Email Template', description: 'Customize the email template used when sending estimates to customers.' },
        { name: 'PDF Branding', description: 'Configure PDF header with company logo, address, and contact details.' },
      ]}
      tabs={['Numbering', 'Defaults', 'PDF Layout', 'Email Template']}
      features={[
        'Custom estimate number format',
        'Default expiry period setting',
        'Configurable T&C text',
        'Email template customization',
        'PDF branding configuration',
        'Default item tax codes',
      ]}
      dataDisplayed={[
        'Current numbering format and last used number',
        'Default expiry days setting',
        'T&C text content',
        'Email template content',
        'PDF branding settings',
      ]}
      userActions={[
        'Set estimate number format and prefix',
        'Change default validity period',
        'Update standard terms and conditions',
        'Customize estimate email template',
        'Update PDF header branding',
      ]}
      relatedPages={[
        { label: 'Estimate List', href: '/sales/estimates/estimate-list' },
        { label: 'Invoices', href: '/sales/billing/invoices' },
      ]}
    />
  )
}

