'use client'

import { useState } from 'react'
import { Calculator, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Active Item', type:Connected, period:'Default', generatedOn:'2026-02-06', generatedBy:'Main'},
    {id:'r2', name:'Default', type:Approved, period:'Monthly', generatedOn:'2026-02-01', generatedBy:'Default'},
    {id:'r3', name:'Default', type:Medium, period:'Q1 2026', generatedOn:'2026-02-04', generatedBy:'Acme Corp'},
    {id:'r4', name:'BPI Account', type:Closed, period:'Metro Manila', generatedOn:'2026-03-06', generatedBy:'Main'},
    {id:'r5', name:'Metro Manila', type:Low, period:'Q1 2026', generatedOn:'2026-01-19', generatedBy:'Monthly'},
    {id:'r6', name:'Primary', type:High, period:'BPI Account', generatedOn:'2026-02-17', generatedBy:'Monthly'},
    {id:'r7', name:'Metro Manila', type:Processing, period:'Sample Entry', generatedOn:'2026-03-28', generatedBy:'Metro Manila'},
    {id:'r8', name:'Primary', type:Pending, period:'Sample Entry', generatedOn:'2026-02-14', generatedBy:'BPI Account'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Fixed Asset Schedule"
      section="Accounting"
      icon={<Calculator size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={['name','period','generatedBy']}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}