'use client'

import { useState } from 'react'
import { Users, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Sample Entry', type:Enabled, period:'Metro Manila', generatedOn:'2026-01-11', generatedBy:'Default'},
    {id:'r2', name:'Sample Entry', type:Approved, period:'Sample Entry', generatedOn:'2026-02-18', generatedBy:'Primary'},
    {id:'r3', name:'Metro Manila', type:Low, period:'Acme Corp', generatedOn:'2026-02-24', generatedBy:'Q1 2026'},
    {id:'r4', name:'Q1 2026', type:Closed, period:'Metro Manila', generatedOn:'2026-02-17', generatedBy:'Q1 2026'},
    {id:'r5', name:'Q1 2026', type:Active, period:'Sample Entry', generatedOn:'2026-01-21', generatedBy:'Default'},
    {id:'r6', name:'Default', type:Closed, period:'Acme Corp', generatedOn:'2026-02-01', generatedBy:'BPI Account'},
    {id:'r7', name:'Metro Manila', type:Approved, period:'Active Item', generatedOn:'2026-03-28', generatedBy:'Metro Manila'},
    {id:'r8', name:'Monthly', type:Draft, period:'Metro Manila', generatedOn:'2026-02-17', generatedBy:'Standard'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Payroll Reports"
      section="Payroll & Workforce"
      icon={<Users size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
