version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: haypbooks
      POSTGRES_PASSWORD: haypbooks
      POSTGRES_DB: haypbooks_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
    name: haypbooks_pgdata
