import type { InvoiceTemplate } from './types'

const now = new Date().toISOString()

export const DEFAULT_TEMPLATES: InvoiceTemplate[] = [
  {
    id: 'builtin-clean',
    name: 'Clean Minimal',
    description: 'Minimalist, simple lines — perfect for professionals and formal documents.',
    icon: '⚪',
    isBuiltIn: true,
    isDefault: true,
    isDraft: false,
    colors: { primary: '#1F2937', accent: '#6B7280', background: '#FFFFFF', text: '#111827' },
    typography: { headingFont: 'Inter', bodyFont: 'Inter', fontSize: 'normal' },
    layoutStyle: 'minimal',
    borderStyle: 'none',
    logoPosition: 'top-left',
    defaults: { paymentTerms: 'net-30', taxTreatment: 'exclusive', defaultTaxRate: 12, currency: 'PHP', language: 'English', decimalPlaces: 2, dateFormat: 'MMM DD, YYYY' },
    sections: { companyLogo: true, customerAddress: true, shippingAddress: false, paymentTermsText: true, notesField: true, bankDetails: false, thankYouMessage: true, termsAndConditions: false, footerNotes: false, qrCode: false },
    defaultMessage: 'Thank you for your business!',
    createdAt: now, updatedAt: now, usageCount: 0,
  },
  {
    id: 'builtin-colorful',
    name: 'Colorful Vibrant',
    description: 'Vibrant accent colors — great for creative businesses and designers.',
    icon: '🎨',
    isBuiltIn: true,
    isDefault: false,
    isDraft: false,
    colors: { primary: '#7C3AED', accent: '#EC4899', background: '#FAFAFA', text: '#1F2937' },
    typography: { headingFont: 'Inter', bodyFont: 'Inter', fontSize: 'normal' },
    layoutStyle: 'modern',
    borderStyle: 'rounded',
    logoPosition: 'top-left',
    defaults: { paymentTerms: 'net-30', taxTreatment: 'exclusive', defaultTaxRate: 12, currency: 'PHP', language: 'English', decimalPlaces: 2, dateFormat: 'MMM DD, YYYY' },
    sections: { companyLogo: true, customerAddress: true, shippingAddress: false, paymentTermsText: true, notesField: true, bankDetails: false, thankYouMessage: true, termsAndConditions: false, footerNotes: true, qrCode: false },
    defaultMessage: 'Thank you for your business! We appreciate working with you.',
    createdAt: now, updatedAt: now, usageCount: 0,
  },
  {
    id: 'builtin-modern',
    name: 'Modern Sleek',
    description: 'Sleek layout with generous whitespace — ideal for modern brands and tech companies.',
    icon: '◆',
    isBuiltIn: true,
    isDefault: false,
    isDraft: false,
    colors: { primary: '#0EA5E9', accent: '#38BDF8', background: '#F8FAFC', text: '#0F172A' },
    typography: { headingFont: 'Inter', bodyFont: 'Inter', fontSize: 'normal' },
    layoutStyle: 'modern',
    borderStyle: 'solid',
    logoPosition: 'top-right',
    defaults: { paymentTerms: 'net-30', taxTreatment: 'exclusive', defaultTaxRate: 12, currency: 'PHP', language: 'English', decimalPlaces: 2, dateFormat: 'MMM DD, YYYY' },
    sections: { companyLogo: true, customerAddress: true, shippingAddress: true, paymentTermsText: true, notesField: true, bankDetails: true, thankYouMessage: true, termsAndConditions: false, footerNotes: false, qrCode: false },
    defaultMessage: 'Thank you for choosing us. Payment is due within {terms}.',
    createdAt: now, updatedAt: now, usageCount: 0,
  },
  {
    id: 'builtin-corporate',
    name: 'Corporate Formal',
    description: 'Structured layout with strong borders — suits law firms and consultants.',
    icon: '🏢',
    isBuiltIn: true,
    isDefault: false,
    isDraft: false,
    colors: { primary: '#1E3A5F', accent: '#2563EB', background: '#FFFFFF', text: '#1E293B' },
    typography: { headingFont: 'Inter', bodyFont: 'Inter', fontSize: 'normal' },
    layoutStyle: 'classic',
    borderStyle: 'double',
    logoPosition: 'top-left',
    defaults: { paymentTerms: 'net-30', taxTreatment: 'exclusive', defaultTaxRate: 12, currency: 'PHP', language: 'English', decimalPlaces: 2, dateFormat: 'MM/DD/YYYY' },
    sections: { companyLogo: true, customerAddress: true, shippingAddress: true, paymentTermsText: true, notesField: true, bankDetails: true, thankYouMessage: false, termsAndConditions: true, footerNotes: true, qrCode: false },
    defaultMessage: 'Please remit payment per the terms indicated above.',
    defaultTerms: 'Late payments are subject to a 1.5% monthly interest charge.',
    createdAt: now, updatedAt: now, usageCount: 0,
  },
  {
    id: 'builtin-creative',
    name: 'Creative Agency',
    description: 'Artistic and unique — perfect for freelancers and creative agencies.',
    icon: '✒',
    isBuiltIn: true,
    isDefault: false,
    isDraft: false,
    colors: { primary: '#F59E0B', accent: '#EF4444', background: '#FFFBF0', text: '#1C1917' },
    typography: { headingFont: 'Inter', bodyFont: 'Inter', fontSize: 'normal' },
    layoutStyle: 'bold',
    borderStyle: 'solid',
    logoPosition: 'top-center',
    defaults: { paymentTerms: 'net-15', taxTreatment: 'exclusive', defaultTaxRate: 12, currency: 'PHP', language: 'English', decimalPlaces: 2, dateFormat: 'MMM DD, YYYY' },
    sections: { companyLogo: true, customerAddress: true, shippingAddress: false, paymentTermsText: true, notesField: true, bankDetails: false, thankYouMessage: true, termsAndConditions: false, footerNotes: true, qrCode: false },
    defaultMessage: 'It was a pleasure working with you. Let\'s create more together!',
    createdAt: now, updatedAt: now, usageCount: 0,
  },
  {
    id: 'builtin-classic',
    name: 'Classic Traditional',
    description: 'Traditional layout with serif aesthetics — timeless and trusted.',
    icon: '📜',
    isBuiltIn: true,
    isDefault: false,
    isDraft: false,
    colors: { primary: '#374151', accent: '#059669', background: '#FEFEFE', text: '#111827' },
    typography: { headingFont: 'Inter', bodyFont: 'Inter', fontSize: 'normal' },
    layoutStyle: 'classic',
    borderStyle: 'solid',
    logoPosition: 'top-left',
    defaults: { paymentTerms: 'net-30', taxTreatment: 'exclusive', defaultTaxRate: 12, currency: 'PHP', language: 'English', decimalPlaces: 2, dateFormat: 'DD/MM/YYYY' },
    sections: { companyLogo: true, customerAddress: true, shippingAddress: false, paymentTermsText: true, notesField: true, bankDetails: true, thankYouMessage: true, termsAndConditions: true, footerNotes: true, qrCode: false },
    defaultMessage: 'Thank you for your valued business.',
    defaultTerms: 'Payment is due as specified. Cheques payable to company name.',
    createdAt: now, updatedAt: now, usageCount: 0,
  },
]

export const EMPTY_TEMPLATE_DEFAULTS: Omit<import('./types').TemplateFormData, 'name' | 'icon'> = {
  description: '',
  isDefault: false,
  isDraft: false,
  colors: { primary: '#10B981', accent: '#059669', background: '#FFFFFF', text: '#111827' },
  typography: { headingFont: 'Inter', bodyFont: 'Inter', fontSize: 'normal' },
  layoutStyle: 'modern',
  borderStyle: 'solid',
  logoPosition: 'top-left',
  logoBase64: undefined,
  logoSize: 'medium',
  logoShowOnPrint: true,
  logoShowOnEmail: true,
  logoShowOnPayor: true,
  defaults: { paymentTerms: 'net-30', taxTreatment: 'exclusive', defaultTaxRate: 12, currency: 'PHP', language: 'English', decimalPlaces: 2, dateFormat: 'MMM DD, YYYY' },
  sections: { companyLogo: true, customerAddress: true, shippingAddress: false, paymentTermsText: true, notesField: true, bankDetails: false, thankYouMessage: true, termsAndConditions: false, footerNotes: false, qrCode: false },
  defaultMessage: 'Thank you for your business!',
}
