'use client'

import PageDocumentation from '@/components/owner/PageDocumentation'

export default function Page() {
  return (
    <PageDocumentation
      title="Invoice Settings"
      module="SALES"
      breadcrumb="Sales / Sales Settings / Invoice Settings"
      purpose="Invoice Settings configures all system-wide defaults for invoicing — including invoice numbering format, default payment terms, default due date calculation, VAT/tax settings, invoice PDF layout and branding, default notes and footer text, and email settings for invoice delivery. Consistent invoice settings ensure all invoices generated by the team are uniform, professional, and compliant with BIR invoice requirements (for Philippine operations)."
      components={[
        { name: 'Numbering Settings', description: 'Invoice number prefix, starting number, and auto-increment pattern. Option to set series per branch or entity.' },
        { name: 'Default Terms', description: 'Set default payment terms applied to all new invoices (overridable per customer).' },
        { name: 'Tax Settings', description: 'Configure default VAT treatment: VAT-inclusive, VAT-exclusive, or VAT-exempt. BIR-required invoice fields (authority to print number, printer accreditation).' },
        { name: 'PDF Layout Builder', description: 'Select invoice template design, upload logo, configure column headers, and set which fields appear on the PDF.' },
        { name: 'Email Template', description: 'Invoice email subject and body template with merge tags for customer name, invoice number, amount, and due date.' },
      ]}
      tabs={['Numbering', 'Defaults', 'Tax Settings', 'PDF Layout', 'Email Template']}
      features={[
        'Invoice numbering format and series management',
        'BIR-compliant invoice fields (for Philippines)',
        'Customizable invoice PDF template',
        'Default VAT and tax treatment settings',
        'Invoice email template customization',
        'Authority to Print (ATP) reference storage',
      ]}
      dataDisplayed={[
        'Current invoice number format',
        'Default terms and tax settings',
        'PDF template preview',
        'Email template content',
        'BIR compliance fields',
      ]}
      userActions={[
        'Update invoice numbering format',
        'Change default payment terms',
        'Configure VAT treatment',
        'Enter BIR Authority to Print number',
        'Customize invoice PDF template',
        'Update invoice email template',
      ]}
      relatedPages={[
        { label: 'Invoices', href: '/sales/billing/invoices' },
        { label: 'Estimate Settings', href: '/sales/estimates/estimate-settings' },
        { label: 'BIR Compliance', href: '/philippine-tax/compliance/bir-compliance' },
      ]}
    />
  )
}

