'use client'

import { useState } from 'react'
import { TrendingUp, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Metro Manila', type:Medium, period:'Active Item', generatedOn:'2026-02-14', generatedBy:'Monthly'},
    {id:'r2', name:'Acme Corp', type:Approved, period:'Active Item', generatedOn:'2026-03-13', generatedBy:'Monthly'},
    {id:'r3', name:'Q1 2026', type:Connected, period:'Sample Entry', generatedOn:'2026-01-20', generatedBy:'Monthly'},
    {id:'r4', name:'Q1 2026', type:Closed, period:'Primary', generatedOn:'2026-02-22', generatedBy:'Acme Corp'},
    {id:'r5', name:'Monthly', type:Active, period:'Q1 2026', generatedOn:'2026-01-22', generatedBy:'Acme Corp'},
    {id:'r6', name:'Standard', type:Connected, period:'Standard', generatedOn:'2026-03-20', generatedBy:'Acme Corp'},
    {id:'r7', name:'BPI Account', type:Paid, period:'Standard', generatedOn:'2026-02-01', generatedBy:'Active Item'},
    {id:'r8', name:'Q1 2026', type:Medium, period:'Active Item', generatedOn:'2026-01-18', generatedBy:'Metro Manila'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Revenue Trends"
      section="Sales & Revenue"
      icon={<TrendingUp size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
