'use client'

import { useState } from 'react'
import { Clock, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Q1 2026', type:Active, period:'Q1 2026', generatedOn:'2026-03-16', generatedBy:'Sample Entry'},
    {id:'r2', name:'Metro Manila', type:Approved, period:'Monthly', generatedOn:'2026-02-07', generatedBy:'Q1 2026'},
    {id:'r3', name:'Standard', type:Active, period:'Default', generatedOn:'2026-02-15', generatedBy:'Primary'},
    {id:'r4', name:'Monthly', type:Closed, period:'Acme Corp', generatedOn:'2026-01-28', generatedBy:'Default'},
    {id:'r5', name:'Standard', type:Pending, period:'Active Item', generatedOn:'2026-01-23', generatedBy:'BPI Account'},
    {id:'r6', name:'Metro Manila', type:Enabled, period:'Sample Entry', generatedOn:'2026-01-12', generatedBy:'Sample Entry'},
    {id:'r7', name:'BPI Account', type:Open, period:'Monthly', generatedOn:'2026-01-01', generatedBy:'Metro Manila'},
    {id:'r8', name:'Q1 2026', type:Processing, period:'Q1 2026', generatedOn:'2026-03-19', generatedBy:'Main'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Time Summary"
      section="Time Tracking"
      icon={<Clock size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
