# HaypBooks Owner Hub - Page Generator (Fixed v3)
param([string]$BatchDir = "")

$base = "C:\Users\HomePC\Desktop\Haypbooksv9\Haypbooks\Frontend\src\app\(owner)"

function To-TitleCase($s){($s -split '-' | ForEach-Object { $_.Substring(0,1).ToUpper()+$_.Substring(1) }) -join ' '}

$icons = @{
    home='LayoutDashboard';accounting='Calculator';sales='TrendingUp';expenses='Receipt';
    'banking-cash'='Landmark';inventory='Package';projects='FolderKanban';'payroll-workforce'='Users';
    taxes='FileText';'philippine-tax'='Building';reporting='BarChart3';settings='Settings';
    compliance='Shield';automation='Zap';'ai-analytics'='Brain';'apps-integrations'='Puzzle';
    'tasks-approvals'='CheckSquare';time='Clock';'financial-services'='Wallet';organization='Network';
    'accountant-workspace'='UserCheck'
}
$labels = @{
    home='Home';accounting='Accounting';sales='Sales & Revenue';expenses='Expenses';
    'banking-cash'='Banking & Cash';inventory='Inventory';projects='Projects';
    'payroll-workforce'='Payroll & Workforce';taxes='Tax';'philippine-tax'='Philippine Tax';
    reporting='Reporting';settings='Settings';compliance='Compliance';automation='Automation';
    'ai-analytics'='AI Analytics';'apps-integrations'='Apps & Integrations';
    'tasks-approvals'='Tasks & Approvals';time='Time Tracking';
    'financial-services'='Financial Services';organization='Organization';
    'accountant-workspace'='Accountant Workspace'
}

# Column definitions - produce proper JSX lines
function Get-Columns($dir) {
    $d = $dir.ToLower()
    if ($d -match 'report|analytics|dashboard|insight|performance|trend|summary|ratio|benchmark|health|help|shortcut|cash.position|business|esg|runway|credit.health') {
        return @(
            "    { key: 'name', label: 'Report', type: 'text', sortable: true }",
            "    { key: 'type', label: 'Type', type: 'badge', badgeColors }",
            "    { key: 'period', label: 'Period', type: 'text' }",
            "    { key: 'generatedOn', label: 'Generated', type: 'date' }",
            "    { key: 'generatedBy', label: 'Generated By', type: 'text' }"
        )
    }
    if ($d -match 'setting|preference|config|custom|profile|fiscal|currenc|numbering|template|pdf|field|notification|security|two.factor|role|permission|setup.center') {
        return @(
            "    { key: 'name', label: 'Setting', type: 'text', sortable: true }",
            "    { key: 'category', label: 'Category', type: 'badge', badgeColors }",
            "    { key: 'value', label: 'Value', type: 'text' }",
            "    { key: 'description', label: 'Description', type: 'text' }",
            "    { key: 'status', label: 'Status', type: 'status', statusColors }"
        )
    }
    if ($d -match 'task|approval|follow.up|exception|todo|calendar|schedule|checklist|sign.off|delegat|workflow|rule|automation.log|error.queue|recurring|report.scheduler|email.notif|smart') {
        return @(
            "    { key: 'name', label: 'Task', type: 'text', sortable: true }",
            "    { key: 'assignee', label: 'Assignee', type: 'text' }",
            "    { key: 'dueDate', label: 'Due Date', type: 'date' }",
            "    { key: 'priority', label: 'Priority', type: 'status', statusColors }",
            "    { key: 'status', label: 'Status', type: 'status', statusColors }"
        )
    }
    if ($d -match 'item|product|service|stock|warehouse|bin|bundle|unit|categor|reorder|safet|lot.serial|cycle.count|adjustment|transfer|physical') {
        return @(
            "    { key: 'name', label: 'Name', type: 'text', sortable: true }",
            "    { key: 'sku', label: 'SKU', type: 'text' }",
            "    { key: 'category', label: 'Category', type: 'badge', badgeColors }",
            "    { key: 'price', label: 'Price', type: 'currency' }",
            "    { key: 'qty', label: 'Quantity', type: 'number' }",
            "    { key: 'status', label: 'Status', type: 'status', statusColors }"
        )
    }
    if ($d -match 'vendor|customer|employee|contractor|user|member|contact|recruit|app|integration|api|webhook|marketplace|connect|discover|developer|sandbox|documentation|installed|sync|entity|legal|consolid|org.chart|department|location|division|class|tag|document.storage|filing|bank.account|cash.account|credit.facil|credit.line|loan|treasury|cash.pool|fx|intercompany|internal.loan|investment|insurance|savings|checking|merchant') {
        return @(
            "    { key: 'name', label: 'Name', type: 'text', sortable: true }",
            "    { key: 'type', label: 'Type', type: 'badge', badgeColors }",
            "    { key: 'contact', label: 'Contact', type: 'text' }",
            "    { key: 'balance', label: 'Balance', type: 'currency' }",
            "    { key: 'status', label: 'Status', type: 'status', statusColors }"
        )
    }
    # Default: financial
    return @(
        "    { key: 'date', label: 'Date', type: 'date', sortable: true }",
        "    { key: 'description', label: 'Description', type: 'text' }",
        "    { key: 'amount', label: 'Amount', type: 'currency', sortable: true }",
        "    { key: 'account', label: 'Account', type: 'text' }",
        "    { key: 'status', label: 'Status', type: 'status', statusColors }"
    )
}

function Get-MockRows($cols, $count=8) {
    $rng = [System.Random]::new()
    $texts = @('Sample Entry','Acme Corp','Metro Manila','BPI Account','Q1 2026','Monthly','Standard','Primary','Active Item','Main','Default','General')
    $statuses = @('Active','Pending','Completed','Open','Closed','Draft','Approved','Filed','Connected','Processing','In Stock','Current','Enabled','Paid','High','Medium','Low')
    $badges = @('Revenue','Operating','Direct','Monthly','Quarterly','Annual','Fixed','Variable','Standard','Premium','Basic')
    
    $rows = @()
    for ($i=0; $i -lt $count; $i++) {
        $parts = @("id: 'r$($i+1)'")
        foreach ($c in $cols) {
            $key = ''
            if ($c -match "key:\s*'([^']+)'") { $key = $Matches[1] }
            $isBadge = $c -match 'badgeColors'
            $type = if ($c -match "type:\s*'date'") { 'date' } elseif ($c -match "type:\s*'currency'") { 'currency' } elseif ($c -match "type:\s*'number'") { 'number' } elseif ($c -match "type:\s*'percentage'") { 'percentage' } elseif ($c -match "type:\s*'status'|type:\s*'badge'") { 'status' } else { 'text' }
            
            switch ($type) {
                'status' {
                    if ($isBadge) { $v = "'$($badges[$rng.Next($badges.Count)])'" }
                    else { $v = "'$($statuses[$rng.Next($statuses.Count)])'" }
                }
                'date' { $d = Get-Date -Year 2026 -Month ($rng.Next(3)+1) -Day ($rng.Next(28)+1); $v = "'$($d.ToString('yyyy-MM-dd'))'" }
                'currency' { $v = ($rng.Next(1,500)*100) }
                'number' { $v = $rng.Next(1,100) }
                'percentage' { $v = $rng.Next(1,20)*5 }
                default { $v = "'$($texts[$rng.Next($texts.Count)])'" }
            }
            $parts += "$key`: $v"
        }
        $rows += "    { $($parts -join ', ') }"
    }
    return $rows -join ",`n"
}

$stubs = Get-ChildItem $base -Recurse -File -Filter "page.tsx" | ForEach-Object {
    $c = Get-Content $_.FullName -Raw -EA 0
    if ($c -match "statusColors=\{\{") {
        $dir = $_.DirectoryName.Replace("$base\","")
        $pt = ($dir -split '\\')[-1]
        [PSCustomObject]@{Path=$_.FullName; Dir=$dir; Title=$pt}
    }
}
if ($BatchDir) { $stubs = $stubs | Where-Object { $_.Dir -match "^$([regex]::Escape($BatchDir))" } }

Write-Output "Generating $($stubs.Count) pages..."
$gen = 0; $err = 0

foreach ($s in $stubs) {
    try {
        $cols = Get-Columns $s.Dir
        $section = ($s.Dir -split '\\')[0]
        $icon = if ($icons.ContainsKey($section)) { $icons[$section] } else { 'FileText' }
        $label = if ($labels.ContainsKey($section)) { $labels[$section] } else { $section }
        $title = To-TitleCase $s.Title
        $mockRows = Get-MockRows $cols
        $colJsx = $cols -join ",`n"
        $hasCur = ($cols | Where-Object { $_ -match "type:\s*'currency'" }).Count -gt 0
        
        $sumBlock = if ($hasCur) {
@"
      summaryCards={[
        { label: 'Total Records', value: 8, icon: <List size={16}/>, bg: 'bg-emerald-100', iconColor: 'text-emerald-600' },
        { label: 'Active', value: 6, icon: <CheckCircle size={16}/>, bg: 'bg-blue-100', iconColor: 'text-blue-600' },
        { label: 'Total Value', value: 'PHP 528,500', icon: <DollarSign size={16}/>, bg: 'bg-amber-100', iconColor: 'text-amber-600' },
        { label: 'This Month', value: 3, icon: <Calendar size={16}/>, bg: 'bg-purple-100', iconColor: 'text-purple-600' },
      ]}
"@ } else {
@"
      summaryCards={[
        { label: 'Total Records', value: 8, icon: <List size={16}/>, bg: 'bg-emerald-100', iconColor: 'text-emerald-600' },
        { label: 'Active', value: 6, icon: <CheckCircle size={16}/>, bg: 'bg-blue-100', iconColor: 'text-blue-600' },
        { label: 'This Month', value: 3, icon: <Calendar size={16}/>, bg: 'bg-amber-100', iconColor: 'text-amber-600' },
      ]}
"@ }
        
        # Determine if we need badgeColors import
        $hasBadge = ($cols | Where-Object { $_ -match 'badgeColors' }).Count -gt 0
        $importLine = if ($hasBadge) { "import { statusColors, badgeColors } from '@/components/owner/statusColors'" } else { "import { statusColors } from '@/components/owner/statusColors'" }
        
        $page = @"
'use client'

import { useState } from 'react'
import { $icon, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'
$importLine

const columns = [
$colJsx
]

const mockData = [
$mockRows
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="$title"
      section="$label"
      icon={<$icon size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={['name', 'description']}
$sumBlock
      bulkActions={[
        { label: 'Export Selected', icon: <Download size={13}/>, onClick: (ids) => {} },
        { label: 'Delete Selected', icon: <Trash2 size={13}/>, onClick: (ids) => {}, variant: 'danger' },
      ]}
      filters={[
        { key: 'date_from', label: 'Date Range', type: 'date-range' },
      ]}
      showCreate
      createLabel="Create New"
      onCreate={() => {}}
      showExport
      onRefresh={() => {}}
      rowMenuItems={(row) => [
        { label: 'View', icon: <Eye size={14}/>, onClick: () => {} },
        { label: 'Edit', icon: <Edit2 size={14}/>, onClick: () => {} },
        { label: 'Delete', icon: <Trash2 size={14}/>, onClick: () => {}, variant: 'danger' },
      ]}
    />
  )
}
"@
        [System.IO.File]::WriteAllText($s.Path, $page, [System.Text.Encoding]::UTF8)
        $gen++
        if ($gen % 100 -eq 0) { Write-Output "  Progress: $gen / $($stubs.Count)" }
    } catch {
        Write-Output "  ERROR: $($s.Dir) - $_"
        $err++
    }
}
Write-Output "`nDone! Generated: $gen, Errors: $err"

