'use client'

import { useState } from 'react'
import { FileText, List, CheckCircle, Calendar, DollarSign, Eye, Edit2, Trash2, Download } from 'lucide-react'
import OwnerPageTemplate from '@/components/owner/OwnerPageTemplate'

const columns = [
    {key:'name',label:'Report',type:'text',sortable:true},
    {key:'type',label:'Type',type:'badge'},
    {key:'period',label:'Period',type:'text'},
    {key:'generatedOn',label:'Generated',type:'date'},
    {key:'generatedBy',label:'Generated By',type:'text'}
]

const mockData = [
    {id:'r1', name:'Sample Entry', type:Approved, period:'Metro Manila', generatedOn:'2026-02-10', generatedBy:'Sample Entry'},
    {id:'r2', name:'Sample Entry', type:Approved, period:'Monthly', generatedOn:'2026-02-13', generatedBy:'Default'},
    {id:'r3', name:'Standard', type:Current, period:'Active Item', generatedOn:'2026-02-23', generatedBy:'Active Item'},
    {id:'r4', name:'Sample Entry', type:Pending, period:'Default', generatedOn:'2026-02-08', generatedBy:'BPI Account'},
    {id:'r5', name:'Sample Entry', type:Paid, period:'Sample Entry', generatedOn:'2026-01-11', generatedBy:'Q1 2026'},
    {id:'r6', name:'BPI Account', type:Processing, period:'Standard', generatedOn:'2026-03-24', generatedBy:'BPI Account'},
    {id:'r7', name:'Sample Entry', type:Closed, period:'Primary', generatedOn:'2026-01-21', generatedBy:'Active Item'},
    {id:'r8', name:'Metro Manila', type:Enabled, period:'Default', generatedOn:'2026-02-07', generatedBy:'Primary'}
]

export default function Page() {
  const [data] = useState(mockData)

  return (
    <OwnerPageTemplate
      title="Annual Tax Summary"
      section="Tax"
      icon={<FileText size={20}/>}
      columns={columns}
      data={data}
      searchable
      searchableFields={[]}
    summaryCards={[
      {label:'Total Records',value:8,icon:<List size={16}/>,bg:'bg-emerald-100',iconColor:'text-emerald-600'},
      {label:'Active',value:6,icon:<CheckCircle size={16}/>,bg:'bg-blue-100',iconColor:'text-blue-600'},
      {label:'This Month',value:3,icon:<Calendar size={16}/>,bg:'bg-amber-100',iconColor:'text-amber-600'},
    ]}
      bulkActions={[
        {label:'Export Selected',icon:<Download size={13}/>,onClick:(ids)=>{}},
        {label:'Delete Selected',icon:<Trash2 size={13}/>,onClick:(ids)=>{},variant:'danger'},
      ]}
      filters={[
        {key:'date_from',label:'Date Range',type:'date-range'},
      ]}
      showCreate
      createLabel="Create New"
      onCreate={()=>{}}
      showExport
      onRefresh={()=>{}}
      rowMenuItems={(row)=>[
        {label:'View',icon:<Eye size={14}/>,onClick:()=>{}},
        {label:'Edit',icon:<Edit2 size={14}/>,onClick:()=>{}},
        {label:'Delete',icon:<Trash2 size={14}/>,onClick:()=>{},variant:'danger'},
      ]}
    />
  )
}
